version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: daily
    labels:
      - dependencies
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch", "version-update:semver-minor"]
  - package-ecosystem: npm
    directory: /wranglerjs
    schedule:
      interval: daily
    labels:
      - dependencies
